# 作業目標:

題目:<br>

array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?

In [25]:
import numpy as np

In [26]:
array1 = np.array([[10, 8], [3, 5]])
array1

array([[10,  8],
       [ 3,  5]])

反矩陣

In [27]:
array2=np.linalg.inv(array1)

In [28]:
array2

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [29]:
array1 @ array2

array([[1., 0.],
       [0., 1.]])

In [30]:
np.dot(array1,array2)

array([[1., 0.],
       [0., 1.]])

2. 運用上列array計算特徵值、特徵向量?

In [31]:
w, v = np.linalg.eig(array1)

In [32]:
print("eigenvalues\n",w)
print("eigenvactors\n",v)

eigenvalues
 [13.  2.]
eigenvactors
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


3. 運用上列array計算SVD?

In [33]:
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))