題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>

In [26]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.19.2


In [27]:
array1 = np.array(range(30))
array2 = np.array([2,3,5])

print( array1 )
print( array2 )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [37]:
np.savez('array.npz',array1,array2)

In [38]:
load_array = np.load( 'array.npz' )
load_array.files

['arr_0', 'arr_1']

In [39]:
print( '新的 npz 檔中第一個元素內容: \n', load_array['arr_0'], '\n' )
print( '新的 npz 檔中第二個元素內容: \n', load_array['arr_1'], '\n' )

新的 npz 檔中第一個元素內容: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

新的 npz 檔中第二個元素內容: 
 [2 3 5] 



In [43]:
np.savez('array.npz', array1=array1, array2=array2)

In [44]:
load_array = np.load( 'array.npz' )
load_array.files

['array1', 'array2']

In [45]:
print( '新的 npz 檔中第一個元素內容: \n', load_array['array1'], '\n' )
print( '新的 npz 檔中第二個元素內容: \n', load_array['array2'], '\n' )

新的 npz 檔中第一個元素內容: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

新的 npz 檔中第二個元素內容: 
 [2 3 5] 



2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [50]:
load_array = np.load('array.npz')
array3 = np.array([[4,5,6],[1,2,3]])
np.savez('new_array.npz',element1=load_array['array1'],element2=load_array['array2'],element3=array3)

In [51]:
load_array1 = np.load('new_array.npz')
load_array1.files

['element1', 'element2', 'element3']

In [52]:
print( '新的 npz 檔內容: ', load_array1.files, '\n' ) 
print( '新的 npz 檔中第一個元素內容: \n', load_array1['element1'], '\n' )
print( '新的 npz 檔中第二個元素內容: \n', load_array1['element2'], '\n' )
print( '新的 npz 檔中第三個元素內容: \n', load_array1['element3'] )

新的 npz 檔內容:  ['element1', 'element2', 'element3'] 

新的 npz 檔中第一個元素內容: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

新的 npz 檔中第二個元素內容: 
 [2 3 5] 

新的 npz 檔中第三個元素內容: 
 [[4 5 6]
 [1 2 3]]
