# [作業目標]

**Hint:**<br>
**NumPy 陣列的常用屬性**

|屬性|說明|
|---|---|
|shape|陣列的形狀|
|ndim|陣列的維度數目，也就是軸(axis)的數目|
|dtype|陣列元素的資料型別|
|size|陣列元素的數目|
|flat|陣列的一維迭代器|
|T|陣列轉置|
|real|陣列元素複數(complex number)的實數部分|
|imag|陣列元素複數(complex number)的虚數部分|
|data|顯示buffer物件，指向陣列資料的開始位址|
|itemsize|每個元素的記憶體使用量|
|nbytes|陣列所有元素的記憶體使用量|
|strides|往相郼元素移動時需要的byte數|

**使用隨機函式產生陣列的元素**<br>

下列是常用的函式及簡介：<br>

|函式|說明|產生數值區間|隨機數資料型別|隨機數分佈|
|---|---|---|---|---|
|rand()|隨機產生指定形狀(shape)的陣列|[0, 1)|浮點數|連續型均勻分布|
|randn()|隨機產生指定形狀(shape)的陣列|(-1, 1)|浮點數|常態分佈|
|randint((low[, high, size, dtype]))|隨機產生設定區間元素|[low, high)|整數|離散型均勻分布|
|random_sample([size])|隨機產生指定大小的一維陣列|[0.0, 1.0)|浮點數|連續型均勻分布|
|random([size])|隨機產生指定大小的一維陣列|[0.0, 1.0)|浮點數|連續型均勻分布|
|randf([size])|隨機產生指定大小的一維陣列|[0.0, 1.0)|浮點數|連續型均勻分布|
|sample([size])|隨機產生指定大小的一維陣列|[0.0, 1.0)|浮點數|連續型均勻分布|

<br><br>

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作


**1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？**

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```
Hint: tolist() 方法可以將NumPy 陣列轉換為列表

In [1]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.19.2


In [4]:
a = np.random.randint(10, size=6) 

print('list(a): ', list(a))
print('tolist(): ', a.tolist())

b = a.reshape(3,2)

print('list(b): ', list(b))
print('b.tolist(): ', b.tolist())

list(a):  [7, 7, 3, 8, 6, 1]
tolist():  [7, 7, 3, 8, 6, 1]
list(b):  [array([7, 7]), array([3, 8]), array([6, 1])]
b.tolist():  [[7, 7], [3, 8], [6, 1]]


**2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）**

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [15]:
a = np.random.randint(10, size=6) 

print('a: ',a)
print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('length: ', len(a))
print('type: ', type(a))
print('data: ', a.data)

a:  [0 9 8 1 3 7]
ndim:  1
shape:  (6,)
size:  6
dtype:  int32
itemsize:  4
length:  6
type:  <class 'numpy.ndarray'>
data:  <memory at 0x00000283F7D05D08>


In [16]:
b = np.random.randint(10, size=(3,4)) 

print('b: \n',b)
print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('length: ', len(b))
print('type: ', type(b))
print('data: ', b.data)

b: 
 [[4 9 3 1]
 [9 9 1 8]
 [8 1 2 6]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int32
itemsize:  4
length:  3
type:  <class 'numpy.ndarray'>
data:  <memory at 0x00000283F6757C18>


In [17]:
c = np.random.randint(10, size=(2,3,2)) 

print('c: \n',c)
print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('length: ', len(c))
print('type: ', type(c))
print('data: ', c.data)

c: 
 [[[2 4]
  [3 2]
  [4 4]]

 [[7 8]
  [6 5]
  [2 8]]]
ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int32
itemsize:  4
length:  2
type:  <class 'numpy.ndarray'>
data:  <memory at 0x00000283F7E48228>


**3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作**

In [18]:
a = np.random.randint(10, size=6)
print('list(a): ', list(a))
print('tolist(): ', a.tolist())

list(a):  [5, 5, 1, 9, 5, 3]
tolist():  [5, 5, 1, 9, 5, 3]


In [19]:
b = np.random.randint(10, size=(3,4)) 
print('list(b): ', list(b))
print('tolist(): ', b.tolist())

list(b):  [array([2, 2, 6, 8]), array([0, 7, 4, 6]), array([8, 4, 9, 8])]
tolist():  [[2, 2, 6, 8], [0, 7, 4, 6], [8, 4, 9, 8]]


In [21]:
c = np.random.randint(10, size=(2,3,2)) 
print('list(c): \n', list(c))
print('tolist(): ', c.tolist())

list(c): 
 [array([[9, 2],
       [4, 2],
       [6, 5]]), array([[2, 2],
       [6, 6],
       [1, 9]])]
tolist():  [[[9, 2], [4, 2], [6, 5]], [[2, 2], [6, 6], [1, 9]]]


In [22]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[5, 5, 1, 9, 5, 3]
[[2, 2, 6, 8], [0, 7, 4, 6], [8, 4, 9, 8]]
[[[9, 2], [4, 2], [6, 5]], [[2, 2], [6, 6], [1, 9]]]
