# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。<br>
3. 承上題，怎樣限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

**1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？**

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.19.2


In [2]:
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


np.zeros((2, 3)) 會產生真正的 0；np.empty((2, 3)) 會產生一個近似於 0 的陣列。<br>
np.empty 可以用於只是想要初始化，但之後就會數值覆寫過的形況。

**2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。**


##  取近似值

取近似值的函式及說明如下表：

|函式|常用語法|說明|
|---|---|---|
|round(), around()|ndarray.round(decimals=0)<br />numpy.round(a, decimals=0)<br />numpy.around(a, decimals=0)|在 Rounding 的方法部分，與 Python 同樣採用 IEEE 754 規範，<br />四捨、五取最近偶數、六入，而非我們一般講的四捨五入。<br /><br />round 與 around 用法及結果相同|
|rint()|numpy.rint(a)|Round至最近的整數|
|trunc()|numpy.trunc(a)|無條件捨去小數點|
|floor()|numpy.floor(a)|向下取整數|
|ceil()|numpy.ceil(a)|向上取整數|
|fix()|numpy.ceil(a)|向0的方向取整數|

In [3]:
a = np.random.rand(2, 3)
a = a * 100

print(a)

[[71.01961829 86.68830592 77.84753929]
 [26.59236146 34.55391717 57.04015258]]


In [4]:
print(a.round())
print(np.round(a))

[[71. 87. 78.]
 [27. 35. 57.]]
[[71. 87. 78.]
 [27. 35. 57.]]


**3. 承上題，怎樣限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。**

In [5]:
m = 20
n = 40

a = np.random.rand(2, 3) * (n - m)
b = a

print((a - b % 1) + m)

[[37. 30. 21.]
 [29. 21. 20.]]
