# [作業目標]:

計算有缺失值的資料，統計量實作<br>


# [作業重點]:

當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>

english_score = np.array([55,89,76,65,48,70])<br>

math_score = np.array([60,85,60,68,np.nan,60])<br>

chinese_score = np.array([65,90,82,72,66,77])<br>

上3列共六位同學的英文、數學、國文成績，

第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，

運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

**1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?**

In [17]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.19.2


In [18]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

**法一**

In [24]:
print("\n英文分數 ","\n平均:",np.nanmean(english_score),"\n最大值:",np.nanmax(english_score),"\n最小值:",np.nanmin(english_score),"\n標準差:",np.nanstd(english_score))
print("\n數學分數 ","\n平均:",np.nanmean(math_score),"\n最大值:",np.nanmax(math_score),"\n最小值:",np.nanmin(math_score),"\n標準差:",np.nanstd(math_score))
print("\n國文分數 ","\n平均:",np.nanmean(chinese_score),"\n最大值:",np.nanmax(chinese_score),"\n最小值:",np.nanmin(chinese_score),"\n標準差:",np.nanstd(chinese_score))


英文分數  
平均: 67.16666666666667 
最大值: 89 
最小值: 48 
標準差: 13.433995020924426

數學分數  
平均: 64.66666666666667 
最大值: 85.0 
最小值: 55.0 
標準差: 9.860132971832694

國文分數  
平均: 75.33333333333333 
最大值: 90 
最小值: 65 
標準差: 8.825468196582484


**法二**

In [20]:
for subject, score in zip(['英文','數學','國文'],[english_score,math_score,chinese_score]):

    if not np.any( np.isnan(score) ) :
        print( subject, ':' )
        print( '平均 =', np.mean(score) )
        print( '最大值 =', np.max(score) )
        print( '最小值 =', np.min(score) )
        print( '標準差 =', np.std(score), '\n' )
    else: 
        print( subject, ':' )
        print( '平均 =', np.nanmean(score) )
        print( '最大值 =', np.nanmax(score) )
        print( '最小值 =', np.nanmin(score) )
        print( '標準差 =', np.nanstd(score), '\n' )

英文 :
平均 = 67.16666666666667
最大值 = 89
最小值 = 48
標準差 = 13.433995020924426 

數學 :
平均 = 66.6
最大值 = 85.0
最小值 = 60.0
標準差 = 9.707728879609279 

國文 :
平均 = 75.33333333333333
最大值 = 90
最小值 = 65
標準差 = 8.825468196582484 



**2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?**

In [21]:
math_score[4] = 55
math_score

array([60., 85., 60., 68., 55., 60.])

In [22]:
print("補考數學後")
print("數學分數 ","\n平均:",np.nanmean(math_score),"\n最大值:",np.nanmax(math_score),"\n最小值:",np.nanmin(math_score),"\n標準差:",np.nanstd(math_score))

補考數學後
數學分數  
平均: 64.66666666666667 
最大值: 85.0 
最小值: 55.0 
標準差: 9.860132971832694


**3. 用補考後資料找出與國文成績相關係數最高的學科?**

In [23]:
print("國文與數學相關係數:\n",np.corrcoef(chinese_score,math_score))
print("國文與英文相關係數:\n",np.corrcoef(chinese_score,english_score))

國文與數學相關係數:
 [[1.         0.74056803]
 [0.74056803 1.        ]]
國文與英文相關係數:
 [[1.         0.97792828]
 [0.97792828 1.        ]]
