# 作業目標:
在array中，可以靈活應用索引幫助資料擷取

作業重點:<br>
陣列的索引、切片(slicing)、以及屬性，皆需要注意使用方式<br>
陣列之中索引由0開始

**Hint:<br>
要用序列數字產生陣列元素的話，可以使用 `arange()` 函式，`arange()` 函式引數如下，其中結束值為必輸，起始值、間隔值非必輸。產生的序列數字包含起始值但不包含結束值，也就是 `[start, stop)` 的表示方式。<br><br>
透過索引存取陣列元素或進行切片 (slicing)，可以使用索引值，或是 [start:stop:step] 語法取得範圍內的元素，要留意的是起始-結束範圍仍是 half-open 的，所以回傳的元素將不包含結束索引的元素。**


題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列<br>
2.承上題，將以上數列取出偶數<br>
3.承1題，將數列取出3的倍數<br>

**1.生成一個等差數列，首數為0，尾數為20，公差為1的數列<br>**

In [7]:
import numpy as np
print( 'NumPy 版本: ', np.__version__ )

NumPy 版本:  1.19.2


In [19]:
Arithmetic_sequence = np.arange(0,21)                          #np.arange(0,21)==np.arange(0,21,1)
Arithmetic_sequence
#print('Arithmetic sequence',Arithmetic_sequence)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

**2.承上題，將以上數列取出偶數**

**法一**

In [21]:
Arithmetic_sequence_even = [i for i in Arithmetic_sequence if i%2==0]
Arithmetic_sequence_even

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

**法二**

In [26]:
Arithmetic_sequence_even = Arithmetic_sequence[::2]
Arithmetic_sequence_even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

**3.承1題，將數列取出3的倍數**

**法一**

In [30]:
Arithmetic_sequence_three = [i for i in Arithmetic_sequence if i>0 and i%3==0]
Arithmetic_sequence_three

[3, 6, 9, 12, 15, 18]

**法二**

In [31]:
Arithmetic_sequence_three = Arithmetic_sequence[3::3]
Arithmetic_sequence_three

array([ 3,  6,  9, 12, 15, 18])