# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？

In [23]:
import numpy as np

**1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。**

In [24]:
a = np.arange(1,12)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
a[(a>=3)&(a<=6)]*=-1
a

array([ 1,  2, -3, -4, -5, -6,  7,  8,  9, 10, 11])

**2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？**

In [26]:
A = np.random.rand(3, 6)
A

array([[0.00786367, 0.75706907, 0.78319899, 0.36080159, 0.21158342,
        0.27171877],
       [0.29940016, 0.91252613, 0.43898867, 0.59745923, 0.35940012,
        0.65190687],
       [0.21256739, 0.31908086, 0.52444919, 0.58267926, 0.04125315,
        0.47550604]])

In [27]:
A[A>0.5]

array([0.75706907, 0.78319899, 0.91252613, 0.59745923, 0.65190687,
       0.52444919, 0.58267926])

In [28]:
A[A>0.5].size

7