# 範例目標:


- `flatten()` 與 `ravel()`
  - 與 `flatten()` 不同的是，`ravel()` 建立的是原來陣列的 view，所以在 `ravel()` 回傳物件中做的元素值變更，將會影響原陣列的元素值
- `reshape()`
  - Reshape 時，新的形狀可以採用模糊指定為 -1，讓 NumPy 自動計算
- `resize()`
  - 如果 resize 的大小超過總元素值，則會在後面的元素值的指定為 0

2. 軸 (axis) 與維度 (dimension)

   - 一維陣列的軸：(axis 為 0)
   - 二維陣列的軸：軸 0 就是沿著 row 的軸，而軸 1 是沿著 column 的軸
   - 三維陣列的軸：軸的順序是"由外而內"、"由row而column"
   - `np.newaxis` 增加軸數<br>
   
   
3. NumPy 陣列的分割與合併

   - 分割：`split()`、`hsplit()`、`vsplit()`<br>
     - indices_or_sections 如果給定單一整數的話，那就會按照軸把陣列等分；如果給定一個 List 的整數值的話，就會按照區段去分割<br><br>
     
   - 合併：`concatenate()`, `stack()`, `hstack()`, `vstack()`<br>
    - stack()` 回傳的陣列維度會是合併前的維度 +1，而 `hstack()` 與 `vstack()` 回傳的陣列維度則是依合併的陣列而定。

      `stack()` 必須要所有陣列的形狀都一樣；而 `hstack()` 與 `vstack()` 則跟上述的規則一樣，除了指定的軸之外，其他軸的形狀必須完全相同才可以合併。

|函式|說明|
|---|---|
|numpy.stack(arrays, axis=0, out=None)|根據指定的軸進行合併|
|numpy.hstack(tup)|根據水平軸進行合併|
|numpy.vstack(tup)|根據垂直軸進行合併|<br>
    
     
     
4. 迭代

   - 多維陣列的迭代則以 axis 0 為準。
   如果要列出多維陣列所有元素的話，可以配合 `flat` 屬性。<br>


5. 搜尋與排序

   - 最大值和最小值：`amax()`、`amin()`、`max()`、`min()`<br>
      基本語法：
      |np.函式|陣列物件.函式|
      |---|---|
      |numpy.amax(array, axis=None, keepdims=<no value>)|ndarray.max(axis=None, keepdims=False)|
      |numpy.amin(array, axis=None, keepdims=<no value>)|ndarray.min(axis=None, keepdims=False)|<br>

   - 最大值和最小值的索引：`argmax()` 與 `argmin()`<br>
      基本語法：

      |np.函式|陣列物件.函式|
      |---|---|
      |numpy.argmax(array, axis=None)|ndarray.argmax(axis=None)|
      |numpy.argmin(array, axis=None)|ndarray.argmin(axis=None)|
    
   - 找出符合條件的元素：`where`<br>
    傳入條件式，回傳值為符合條件的元素索引<br>
    
   - `nonzero`

     - `nonzero` 等同於 `np.where(array != 0)` 的語法，同樣的也是回傳符合非 0 條件的元素索引值。<br>
    語法：

    |np.函式|陣列物件.函式|
    |---|---|
    |numpy.nonzero(array)|ndarray.nonzero()|
     
   - 排序：`sort()` 與 `argsort()`

     要對陣列進行排序可以使用 `sort()` 與 `argsort()`，兩者的差異是在 `sort()` 回傳的是排序後的陣列，<br>
    而 `argsort()` 回傳的是排序後的陣列索引值。

      語法：

|np.函式|陣列物件.函式|
|---|---|
|numpy.sort(a, axis=-1, kind=None, order=None)|ndarray.sort()|
|numpy.argsort(a, axis=-1, kind=None, order=None)|ndarray.argsort()|
   
與 `np.sort()` 不同的是，`陣列物件.sort()` 的語法會進行 in-place 排序，也就是原本的陣列內容會跟著改變。
    
排序支援多種不同的排序算法，包括 quicksort (預設)、heapsort、mergesort、timesort，在 `kind` 引數指定即可。<br>
依照官網文件指出排序速度是以 **quicksort 最快，mergesort / timesort 其次，之後是 heapsort。**
    


# [教學目標]

* 認識 NumPy 中提供的資料型態
* 了解各種型態的差異與定義
* 正確的比較型態判斷
 - 陣列的常用屬性
 - numpy 中的型態判斷
 - 資料型態的正確用法
* **陣列中的統計方法 :**
  - `.sum()`<br>
  - `.min()`<br>
  - `.max()`<br>
* 一種功能，三種函式  
* 陣列中的軸參數 
* 搜尋與排序方法
* `np.sort`
* `np.searchsorted`
* reshape 和 resize
* 三種陣列攤平用法

### `flatten()` 與 `ravel()`<br>

透過 `flatten()` 與 `ravel()` 均可將多維陣列轉形為一維陣列，`flatten()` 與 `ravel()` 的使用透過下列兩種方法，得到的結果都是完全一樣的。

|np.函式|陣列物件.函式|
|---|---|
|np.flatten(a, order='C')|a.flatten(order='C')|
|np.ravel(a, order='C')|a.ravel(order='C')|

與 `flatten()` 不同的是，`ravel()` 建立的是原來陣列的 view，所以在 `ravel()` 回傳物件中做的元素值變更，將會影響原陣列的元素值。<br>

`ravel()`**會改變原陣列值**

`ndarray.flatten(order='C')`

 ‘C’ means to flatten in row-major (C-style) order.<br>
 ‘F’ means to flatten in column-major (Fortran- style) order. <br>
 ‘A’ means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise. <br>
 ‘K’ means to flatten a in the order the elements occur in memory. The default is ‘C’.<br>



In [1]:
import numpy as np
a = np.array([[ 0,  1,  2,  3], 
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
b=a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
c=a.ravel()
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
b[3]=100
b

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [7]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
c[3]=100
c

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [9]:
a

array([[  0,   1,   2, 100],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

```flat```

In [10]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
x.flat[3] # 返回重組後的一維數組下標為3的元素

4

In [12]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
x.T.flat[3]

5

In [14]:
x.flat = 3 # 將數組的元素均變為3
x

array([[3, 3, 3],
       [3, 3, 3]])

In [15]:
x.flat[[1,4]] = 1 # 將數組重组後的一維數組小標為1,4的元素變為1
x

array([[3, 1, 3],
       [3, 1, 3]])

### `reshape()`

`reshape()` 的使用，可以透過 `np.reshape(a, new_shape)` 或 `a.reshape(new_shape, refcheck=True)` 來執行。

Reshape 時，新的形狀可以採用模糊指定為 -1，讓 NumPy 自動計算。

若 reshape 後的陣列元素值改變，會影響原陣列對應的元素值也跟著改變。

In [16]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
a.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [18]:
b = a.reshape((3, 5))
b[0, 2] = 100
b

array([[  0,   1, 100,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [19]:
a

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

###  `resize()`

`resize()` 的使用，也同樣可以透過 `np.resize(a, new_shape)` 或 `a.resize(new_shape, refcheck=True)` 來執行。

要改變被 reference 的陣列時有可能會產生錯誤，這時候可以將 `refcheck` 引數設為 `False` (預設為 `True`)。

如果 resize 的大小超過總元素值，則會在後面的元素值的指定為 0。

In [20]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
a.resize((3, 6), refcheck=False)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14,  0,  0,  0]])

## 軸 (axis) 與維度 (dimension)

軸 (axis) 在 NumPy 多維陣列中是很重要觀念，但是在應用上容易混淆。軸的數目也就是 NumPy 陣列的維度 (dimension) 數，軸的順序編號從 0 開始

### 一維陣列的軸

對一維陣列來說，只有一個軸，所以 axis 為 0。

In [22]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

### 二維陣列的軸

二維陣列的 ndim 為 2，也就是會有 2 個軸。二維陣列的**軸 0 就是沿著 row 的軸，而軸 1 是沿著 column 的軸。**

In [23]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

### 三維陣列的軸

三維陣列有 3 個軸。可以理解**軸的順序是"由外而內"、"由row而column"。**

三維陣列的例子，可以理解為 2 個 4 $\times$ 3 的二維陣列排在一起。

In [24]:
a = np.array([[[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]],
              [[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
a.shape

(2, 4, 3)

若我們要沿軸對元素做加總，呼叫 `sum()` 函式並指定 axis。

In [26]:
a.sum(axis=0)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

### `np.newaxis` 增加軸數

跟 `reshape()` 類似的應用，如果是要增加軸數的話，可以使用 `np.newaxis` 物件。將 `np.newaxis` 加到要增加的軸的位置即可。

與 `reshape()` 不同的地方在於，`np.newaxis` 新增的維度為 1，而 `reshape()` 可以指定要改變的形狀 (不一定為 1)。

In [27]:
a = np.arange(12).reshape(2, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [28]:
a[:,np.newaxis,:].shape

(2, 1, 6)

# NumPy 陣列的合併與分割

### 合併：`concatenate()`, `stack()`, `hstack()`, `vstack()`

使用 `concatenate()` 進行陣列的合併時，須留意除了指定的軸之外 (預設為 axis 0)，其他軸的形狀必須完全相同，合併才不會發生錯誤。

```python
numpy.concatenate((a1, a2, ...), axis=0, out=None)
```

`stack()`, `hstack()`, `vstack()` 的觀念及用法類似，不同點在於 `stack()` 回傳的陣列維度會是合併前的維度 +1，而 `hstack()` 與 `vstack()` 回傳的陣列維度則是依合併的陣列而定。

至於是否可以合併，`stack()` **必須要所有陣列的形狀都一樣**；而 `hstack()` 與 `vstack()` 則跟上述的規則一樣，**除了指定的軸之外，其他軸的形狀必須完全相同才可以合併。**

|函式|說明|
|---|---|
|numpy.stack(arrays, axis=0, out=None)|根據指定的軸進行合併|
|numpy.hstack(tup)|根據水平軸進行合併|
|numpy.vstack(tup)|根據垂直軸進行合併|

In [29]:
a = np.arange(10).reshape(5, 2)
b = np.arange(6).reshape(3, 2)
print('a:\n',a)
print('b:\n',b)

a:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
b:
 [[0 1]
 [2 3]
 [4 5]]


In [30]:
np.concatenate((a,b), axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [31]:
#stack() 必須要所有陣列的形狀都一樣
c = np.arange(10).reshape(5, 2)
np.stack((a, c), axis=1)

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 7],
        [6, 7]],

       [[8, 9],
        [8, 9]]])

In [32]:
#根據水平軸進行合併
d = np.arange(5).reshape(5, 1)
np.hstack((a, d))

array([[0, 1, 0],
       [2, 3, 1],
       [4, 5, 2],
       [6, 7, 3],
       [8, 9, 4]])

In [33]:
#根據垂直軸進行合併
np.vstack((a, b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

### 分割：`split()`、`hsplit()`、`vsplit()`

`split()` 的語法：

```python
numpy.split(array, indices_or_sections, axis=0)
```

indices_or_sections 如果給定單一整數的話，那就會按照軸把陣列等分；如果給定一個 List 的整數值的話，就會按照區段去分割，例如：
`indices_or_sections=[2, 3]` 會照下列的方式做分割 (一樣是照按照軸把陣列分割)
```
ary[:2]
ary[2:3]
ary[3:]
```

與 `split` 很類似的是 `hsplit` 與 `vsplit`，分別是依照水平軸和垂直軸去做分割。

In [34]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
np.split(a,5)

[array([[0, 1]]),
 array([[2, 3]]),
 array([[4, 5]]),
 array([[6, 7]]),
 array([[8, 9]])]

In [36]:
# split 為 (2,2), (1,2), (2,2) 三個陣列，並回傳含 3 個陣列的 List
np.split(a, [2,3])

[array([[0, 1],
        [2, 3]]),
 array([[4, 5]]),
 array([[6, 7],
        [8, 9]])]

In [37]:
b = np.arange(30).reshape(5, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
# 依水平軸去做等分分割
np.hsplit(b, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

In [39]:
# 依水平軸照區段去分割
np.hsplit(b, [2, 3, 5])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2],
        [ 8],
        [14],
        [20],
        [26]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29]])]

In [40]:
# 依垂直軸按照區段去分割，超出的區段則傳回空陣列
np.vsplit(b, [2, 4, 6])

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([], shape=(0, 6), dtype=int32)]

## 迭代

一維陣列的迭代，跟 Python 集合型別 (例如 List) 的迭代相同。

多維陣列的迭代則以 axis 0 為準。以二維陣列為例，列出各 row 的元素。

如果要列出多維陣列所有元素的話，可以配合 `flat` 屬性。

In [41]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [42]:
for i in a:
    print(i)

0
1
2
3
4


In [43]:
for row in b:
    print(row)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


In [44]:
for i in b.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


## 搜尋與排序

### 顯示最大值和最小值：`amax()`、`amin()`、`max()`、`min()`

要顯示陣列元素最大值和最小值，可以透過 `amax()`、`amin()`、`max()`、`min()`，也可以依照軸列出各軸的最大/最小元素值。

基本語法：

|np.函式|陣列物件.函式|
|---|---|
|numpy.amax(array, axis=None, keepdims=<no value>)|ndarray.max(axis=None, keepdims=False)|
|numpy.amin(array, axis=None, keepdims=<no value>)|ndarray.min(axis=None, keepdims=False)|<br><br>
    

如果是多維陣列的話，用法也是相同，也可以依照軸列出最大或最小值。

In [45]:
a = np.random.randint(1, 20, 10)
a   

array([ 4, 15, 13, 14, 14,  9, 17, 12, 19, 19])

In [46]:
# 陣列中最大的元素值
np.amax(a)

19

In [47]:
# 陣列中最小的元素值
np.amin(a)

4

In [48]:
b = a.reshape(2, 5)
b

array([[ 4, 15, 13, 14, 14],
       [ 9, 17, 12, 19, 19]])

In [49]:
# 若設定 keepdims=True，結果會保留原陣列的維度來顯示。
np.amax(b, keepdims=True)

array([[19]])

In [50]:
# 列出各 row 最大值
b.max(axis=1)

array([15, 19])

In [51]:
# 同樣的 amax 也可以依軸列出各 row 最大值
np.amax(b, axis=1)

array([15, 19])

In [52]:
# 列出各 column 最小值
b.min(axis=0)

array([ 4, 15, 12, 14, 14])

### 顯示最大值和最小值的索引：`argmax()` 與 `argmin()`

`argmax` / `argmin` 和上述不同的地方在於，`argmax` / `argmin` 回傳的是**最大值和最小值的索引**，也可以依照軸找出各軸最大值和最小值的索引。

基本語法：

|np.函式|陣列物件.函式|
|---|---|
|numpy.argmax(array, axis=None)|ndarray.argmax(axis=None)|
|numpy.argmin(array, axis=None)|ndarray.argmin(axis=None)|

若沒有指定軸的話，`argmax()` 與 `argmin()` 會回傳多維陣列展平後的索引。

In [53]:
np.random.seed(0)
a = np.random.randint(1, 20, size=(3, 4))
a

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [54]:
np.argmax(a)

7

In [55]:
a.argmin()

2

### 找出符合條件的元素：`where`

語法：
```python
numpy.where(condition[, x, y])
```

傳入條件式，回傳值為符合條件的元素索引，不過這邊留意的是，以下面二維陣列為例，回傳的索引陣列要合併一起看，也就是說
```
(array([0, 0, 1, 2]), 
 array([0, 1, 3, 2]))
```

a[0, 0] 值為 13<br />
a[0, 1] 值為 16<br />
a[1, 3] 值為 19<br />
a[2, 2] 值為 13

以上索引值對應的元素，其值都符合 "大於 10" 的條件。

In [56]:
np.where(a > 10)

(array([0, 0, 1, 2], dtype=int64), array([0, 1, 3, 2], dtype=int64))

若是設定 x, y 引數的話，可將各元素取代掉。以下面的例子來解釋，如果元素值大於 10 的話就用 "Y" 來替代，反之則是 "N"。

In [57]:
np.where(a > 10, "Y", "N")

array([['Y', 'Y', 'N', 'N'],
       ['N', 'N', 'N', 'Y'],
       ['N', 'N', 'Y', 'N']], dtype='<U1')

###  `nonzero`

`nonzero` 等同於 `np.where(array != 0)` 的語法，同樣的也是回傳符合非 0 條件的元素索引值。

語法：

|np.函式|陣列物件.函式|
|---|---|
|numpy.nonzero(array)|ndarray.nonzero()|

`np.nonzero(a)` == `a.nonzero()`<br>

### 排序：`sort()` 與 `argsort()`

要對陣列進行排序可以使用 `sort()` 與 `argsort()`，兩者的差異是在 `sort()` 回傳的是**排序後的陣列**，而 `argsort()` 回傳的是**排序後的陣列索引值。**

語法：

|np.函式|陣列物件.函式|
|---|---|
|numpy.sort(a, axis=-1, kind=None, order=None)|ndarray.sort()|
|numpy.argsort(a, axis=-1, kind=None, order=None)|ndarray.argsort()|

與 `np.sort()` 不同的是，`陣列物件.sort()` 的語法會進行 in-place 排序，也就是原本的陣列內容會跟著改變。

多維陣列在排序時可以指定要依據的軸。

排序支援多種不同的排序算法，包括 quicksort (預設)、heapsort、mergesort、timesort，在 `kind` 引數指定即可。依照官網文件指出排序速度是以 quicksort 最快，mergesort / timesort 其次，之後是 heapsort。

In [58]:
np.random.seed(3)
a = np.random.randint(0, 20, 10)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6])

In [59]:
b=np.sort(a)
b

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [60]:
#與 np.sort() 不同的是，陣列物件.sort()的語法會進行 in-place 排序，也就是原本的陣列內容會跟著改變。
a.sort()
a

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [61]:
c = np.random.randint(0, 100000000, 1000000)
np.sort(c, kind='heapsort')

array([      64,       96,      310, ..., 99999479, 99999561, 99999830])

# Numpy運算

In [62]:
# 從一個陣列開始

a = np.arange(15).reshape(3, 5)
print(a) # 利用 print(...) 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
# 陣列的常用屬性

print(a.dtype) # int64
print(a.itemsize) # 8


int32
4


In [64]:
# numpy 中的型態判斷

print(a.dtype == 'int32') 
print(a.dtype is 'int32') 
print(a.dtype is np.int32) 


True
False
False


In [65]:
# 資料型態的正確用法

print(a.dtype == 'int32') # True
print(a.dtype == np.int32) # True
print(a.dtype is np.dtype('int32')) # True

True
True
True


# NumPy 運算 - 1

**陣列中的統計方法 :**

`.sum()`<br>
`.min()`<br>
`.max()`<br>


In [66]:
# 陣列中的統計方法


a = np.arange(6)
print(a)

print(a.sum()) 
print(a.min()) 
print(a.max()) 

[0 1 2 3 4 5]
15
0
5


**一種功能，三種函式**

In [67]:
# 一種功能，三種函式


a = np.arange(6)

print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

15
15
15


**陣列中的軸參數**

In [68]:
# 陣列中的軸參數

b = np.arange(12).reshape(3, 4)

print(b)
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


**搜尋與排序方法**

In [69]:
# 搜尋與排序方法

import numpy as np 

a = np.array([1, 3, 2, 5, 4])
print(a.sort())
print(a)

None
[1 2 3 4 5]


`np.sort`

In [70]:
import numpy as np 

a = np.array([1, 3, 2, 5, 4])
print(np.sort(a))
print(a)

[1 2 3 4 5]
[1 3 2 5 4]


`np.searchsorted`

In [71]:
import numpy as np 

print(np.searchsorted([1,2,3,4,5], 3))
print(np.searchsorted(
    [1, 2, 3, 4, 5],
    [-10, 10, 3, 5]
))


2
[0 5 2 4]


**reshape 和 resize**

In [72]:
# reshape 和 resize

import numpy as np 

a = np.arange(6)

print(a)
print(a.reshape(3, 2))
print(a)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [73]:
import numpy as np 

a = np.arange(6)

print(a)
print(a.resize((3, 2)))
print(a)

[0 1 2 3 4 5]
None
[[0 1]
 [2 3]
 [4 5]]


**三種陣列攤平用法**

In [74]:
# 三種陣列攤平用法

import numpy as np 

a = np.arange(6).reshape((3, 2))

print(a.ravel() )
print(a.flatten())
print(a.flat)
print(list(a.flat))

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0, 1, 2, 3, 4, 5]
