# 範例重點:

陣列進行 element-wise 的操作，並回傳陣列，稱為 Universal Functions (ufunc)

在做四則運算時，應注意**維度需要相等**

##  四則運算

陣列的加減乘除四則運算，可以使用運算子 (+, -, *, /) 或是呼叫函式來進行，語法及對照如下表：

|運算子|函式||
|---|---|---|
|a + b |np.add(a, b)|加法|
|a - b |np.substract(a, b)|減法|
|a * b |np.multiply(a, b)|乘法|
|a / b |np.divide(a, b)|除法|
|a % b |np.mod(a, b)|求餘數|

以上運算子的部分，使用與 Python 相同的運算子。

運算的時候，陣列的形狀 (shape) 必須相同，或是遵循廣播 (broadcastiing) 規則，才能正確進行 **element-wise 運算**。

規則如下：
- 兩個陣列形狀完全相同
- 比較兩個陣列的維度，如果維度的形狀相同的話，可以進行廣播
- 比較兩個陣列的維度，其中一個維度為1的話，可以進行廣播

若是兩個陣列形狀不相同的話，遵循廣播規則，下面的例子可以正常運算。<br>


- `sum()`
- 次方 `np.power()`

|運算子|函式|a 的 b 次方|
|---|---|---|
|a ** b |np.power(a, b)|$a^b$|

- 平方根 `np.sqrt()`
- 歐拉數 (Euler's number) 及指數函式 `np.exp()`
  - NumPy 提供歐拉常數 $e$，以及指數函式 `np.exp()`，表示 $e^x$<br>
  
- 對數函式

|函式||
|---|---|
|np.log(x)|底數為e|
|np.log2(x)|底數為2|
|np.log10(x)|底數為10|
|np.log1p(x)|底數為e，計算log(1+x)|

- 近似值

|函式|常用語法|說明|
|---|---|---|
|round(), around()|ndarray.round(decimals=0)<br />numpy.round(a, decimals=0)<br />numpy.around(a, decimals=0)|在 Rounding 的方法部分，與 Python 同樣採用 IEEE 754 規範，<br />四捨、五取最近偶數、六入，而非我們一般講的四捨五入。<br /><br />round 與 around 用法及結果相同|
|rint()|numpy.rint(a)|Round至最近的整數|
|trunc()|numpy.trunc(a)|無條件捨去小數點|
|floor()|numpy.floor(a)|向下取整數|
|ceil()|numpy.ceil(a)|向上取整數|
|fix()|numpy.ceil(a)|向0的方向取整數|

- 取絕對值：`np.abs()`, `np.absolute()`, `np.fabs()`<br>
`np.abs()`==`np.absolute()` <br>
`np.fabs()` 無法處理複數 (Complex)

# [教學目標]

* 能夠使用不同的方法初始化一個陣列
* 知道固定大小對於陣列的意義
* 了解不同的亂數陣列有什麼差異
 - 內建型態做轉換
 - 會自動轉換成範圍比較大的型態，也可以指定成想要的型態
 - 字典型態被轉成陣列不符合期待，正確的寫法應該寫**轉成有序的 List 再作轉換**
 - 從固定大小的初始值開始
 - np.zeros 和 np.empty
 - 從固定大小的序列值開始
 - 從固定大小的亂數值開始（新版）
 - 從固定大小的亂數值開始（舊版）

若是兩個陣列形狀不相同的話，遵循廣播規則，下面的例子可以正常運算。<br>
雖然 c 跟 e 的形狀不同，但是從各個維度的形狀比較後發現也是符合規則，還是可以進行運算。

In [36]:
import numpy as np

In [37]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
e = np.random.randint(1, 10, 20).reshape(2, 10)
e

array([[5, 7, 1, 4, 2, 7, 7, 8, 5, 2],
       [1, 2, 5, 4, 6, 1, 7, 6, 5, 8]])

In [39]:
c + e

array([[ 5,  8,  3,  7,  6, 12, 13, 15, 13, 11],
       [ 1,  3,  7,  7, 10,  6, 13, 13, 13, 17]])

##  `sum()`

`sum()` 函式可以根據依指定的軸計算陣列元素值加總，基本語法如下：

```python
numpy.sum(a, axis=None, dtype=None, keepdims=<no value>)
```

若沒有指定軸的話，則是回傳所有元素加總值

numpy.sum(a) == a.sum()

## 次方 `np.power()`

次方的運算，跟四則運算一樣，也要遵循上述的規則，才能成功進行運算。語法如下表：

|運算子|函式|a 的 b 次方|
|---|---|---|
|a ** b |np.power(a, b)|$a^b$|

In [40]:
# 與 2**3 相同
np.power(2, 3)

8

## 平方根 `np.sqrt()`

In [41]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

## 歐拉數 (Euler's number) 及指數函式 `np.exp()`

NumPy 提供歐拉常數 $e$，以及指數函式 `np.exp()`，表示 $e^x$。

In [43]:
np.e

2.718281828459045

In [44]:
np.exp(np.arange(5))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## 對數函式

|函式||
|---|---|
|np.log(x)|底數為e|
|np.log2(x)|底數為2|
|np.log10(x)|底數為10|
|np.log1p(x)|底數為e，計算log(1+x)|

若是 log(負數) 則會產生 nan 常數，NaN / NAN / nan (not a number) 

In [45]:
# 以 np.log10() 為例
np.log10(np.array([1, 10, 100, 1000, 10000]))

array([0., 1., 2., 3., 4.])

若要使用其他底數，可以用下列的方法 (以底數 3 為例)。

In [46]:
np.log(9)/np.log(3)

2.0

In [47]:
import warnings
warnings.filterwarnings('ignore')
np.log([-1, 1, 2])

array([       nan, 0.        , 0.69314718])

##  取近似值

取近似值的函式及說明如下表：

|函式|常用語法|說明|
|---|---|---|
|round(), around()|ndarray.round(decimals=0)<br />numpy.round(a, decimals=0)<br />numpy.around(a, decimals=0)|在 Rounding 的方法部分，與 Python 同樣採用 IEEE 754 規範，<br />四捨、五取最近偶數、六入，而非我們一般講的四捨五入。<br /><br />round 與 around 用法及結果相同|
|rint()|numpy.rint(a)|Round至最近的整數|
|trunc()|numpy.trunc(a)|無條件捨去小數點|
|floor()|numpy.floor(a)|向下取整數|
|ceil()|numpy.ceil(a)|向上取整數|
|fix()|numpy.ceil(a)|向0的方向取整數|

In [48]:
a = np.array([1.65, 1.55, -3.57, 2.0])
a

array([ 1.65,  1.55, -3.57,  2.  ])

In [49]:
np.round(a, decimals=1)

array([ 1.6,  1.6, -3.6,  2. ])

`np.rint(a)` 與 `np.round(a, 0)` 的結果完全相同。

In [50]:
# Round至最近的整數
np.rint(a)

array([ 2.,  2., -4.,  2.])

In [51]:
# Round至最近的整數
np.round(a, 0)

array([ 2.,  2., -4.,  2.])

In [52]:
# 無條件捨去小數點
np.trunc(a)

array([ 1.,  1., -3.,  2.])

In [53]:
# 向下取整數
np.floor(a)

array([ 1.,  1., -4.,  2.])

In [54]:
# 向上取整數
np.ceil(a)

array([ 2.,  2., -3.,  2.])

In [55]:
# 向0的方向取整數
np.fix(a)

array([ 1.,  1., -3.,  2.])

## 取絕對值：`np.abs()`, `np.absolute()`, `np.fabs()`

`np.abs()` 是 `np.absolute()` 的簡寫，兩者完全相同；`np.fabs()` 的差異在於無法處理複數 (Complex)。

如果傳入複數至 fabs() 的話則會產生錯誤。

In [56]:
np.fabs(1+2j)

TypeError: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

# NumPy 運算

字典型態轉成有序的 List 再作轉換

**內建型態做轉換**

In [1]:
# 內建型態做轉換

import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

**會自動轉換成範圍比較大的型態**<br>
**也可以指定成想要的型態**

In [2]:
# 會自動轉換成範圍比較大的型態：

print(np.array([1, 2, 3.0]), np.array([1, 2, 3.0]).dtype)

# 也可以指定成想要的型態：

print(np.array([1, 2, 3], dtype=complex), np.array([1, 2, 3], dtype=complex).dtype)

[1. 2. 3.] float64
[1.+0.j 2.+0.j 3.+0.j] complex128


**字典型態被轉成陣列不符合期待**<br>
**正確的寫法應該寫轉成有序的 List 再作轉換**

In [ ]:
# 字典型態被轉成陣列不符合期待

print(np.array({0: 123, 1: 456}))
print(np.array({0: 123, 1: 456}).size)

# 正確的寫法應該寫轉成有序的 List 再作轉換

print(np.array(list({0: 123, 1: 456}.items())))
print(np.array(list({0: 123, 1: 456}.items())).size)

**從固定大小的初始值開始**

In [ ]:
# 從固定大小的初始值開始
print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.full((2, 3), 9))

**np.zeros 和 np.empty** 

In [ ]:
# np.zeros 和 np.empty 

print(np.zeros((2, 3)))
print(np.empty((2, 3)))

**從固定大小的序列值開始**

In [ ]:
# 從固定大小的序列值開始

print(np.arange( 10, 30, 5 ))
print(np.linspace( 0, 2, 3 ))
print(np.logspace( 0, 2, 3 ))

**從固定大小的亂數值開始（新版）**

In [ ]:
## 從固定大小的亂數值開始（新版）

from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2))
random = rng.random((3,2))
integers = rng.integers(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

**從固定大小的亂數值開始（舊版）**

In [ ]:
## 從固定大小的亂數值開始（舊版）

normal = np.random.randn(2, 3)
random = np.random.random((3,2))
integers = np.random.randint(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)