# NumPy 的矩陣函式與線性代數應用

# 範例目標:

1. 矩陣乘積 : 點積、內積、外積、矩陣乘法<br>
   - 點積：`numpy.dot(a, b)`
   - 內積(純量積)：`numpy.inner()`
   - 外積：`numpy.outer()`
   - 矩陣乘法：`numpy.matmul()` 與 `@`
     * **如果2個都是二維陣列的話，`matmul`與 `dot` 相同。**
     * 在 `matmul` 中，多維的矩陣，將前 n-2 維視為後2维的元素後，進行乘法運算。
     * **`matmul` 不允許矩陣與純量相乘。**<br>
     


2. 矩陣操作 :　跡、行列式、反矩陣、轉置、特徵值與特徵向量、秩、線性系統求解<br>
   - 跡：`numpy.trace()`
     $
     A = \begin{bmatrix}
     a_{11} & a_{12} & a_{13} \\
     a_{21} & a_{22} & a_{23} \\
     a_{31} & a_{32} & a_{33}
     \end{bmatrix}
     $

     $
     trace(A) = a_{11} + a_{22} + a_{33}
     $
   <br>
   - 行列式 (Determinant)：`numpy.linalg.det()`

     **矩陣必為方陣 (square)**

     $\vert A \vert= \begin{vmatrix}
     a_{11} & a_{12} & a_{13} \\
     a_{21} & a_{22} & a_{23} \\
     a_{31} & a_{32} & a_{33}
     \end{vmatrix}\\
     = a_{11}\space a_{22}\space a_{33} + a_{12}\space a_{23}\space a_{31} + a_{13}\space a_{21}\space a_{32}
     - a_{13}\space a_{22}\space a_{31} - a_{23}\space a_{32}\space a_{11} - a_{33}\space a_{12}\space a_{21}
     $

     圖解行列式運算 
     ![](https://upload.wikimedia.org/wikipedia/commons/4/4d/Determinant-columns.png)
<br>
   - 反矩陣：`numpy.linalg.inv()`

     **矩陣必為方陣 (square)**

     $
     A = \left[\begin{array}{ccc|ccc}
     a_{11} & a_{12} & a_{13} & 1 & 0 & 0\\
     a_{21} & a_{22} & a_{23} & 0 & 1 & 0\\
     a_{31} & a_{32} & a_{33} & 0 & 0 & 1
     \end{array}\right]
     $

     透過高斯消去法 (Gaussian Elimination)，可以得到右邊的矩陣即為 A 的反矩陣

     $
     A^{-1} = \left[\begin{array}{ccc|ccc}
     1 & 0 & 0 & b_{11} & b_{12} & b_{13} \\
     0 & 1 & 0 & b_{21} & b_{22} & b_{23}\\
     0 & 0 & 1 & b_{31} & b_{32} & b_{33}
     \end{array}\right]
     $ 
     <br>
   - 轉置 (Transpose)：`numpy.transpose()`

     $
     A = \begin{bmatrix}
     a_{11} & a_{12} & a_{13} \\
     a_{21} & a_{22} & a_{23} \\
     a_{31} & a_{32} & a_{33}
     \end{bmatrix}
     $

     $
     A^T = \begin{bmatrix}
     a_{11} & a_{21} & a_{31} \\
     a_{12} & a_{22} & a_{23} \\
     a_{13} & a_{23} & a_{33}
     \end{bmatrix}
     $
     <br>
   - 特徵值(eigenvalues)與特徵向量(eigenvectors)：`numpy.linalg.eig()`

     ```python
     eigenvalues, eigenvectors = np.linalg.eig(x)
     ```

     `eigvals()` 函式也可以計算特徵值。
    <br>
     
   - 秩：`numpy.linalg.matrix_rank()`
      
      呼叫 `matrix_rank()` 回傳矩陣的秩(rank)，

      NumPy是使用SVD(奇異值分解；singular value decomposition)來計算秩。
   <br>
   - 解線性方程式：`numpy.linalg.solve()`

     
3. 特殊矩陣 : 單位矩陣(identity)、單位矩陣(eye)、三角矩陣、單對角陣列、上三角矩陣、下三角矩陣

   - 單位矩陣：`numpy.identity()`

     單位矩陣是對角線元素值為1的方陣。
    
   - 單位矩陣：`numpy.eye()`

     ```python
     numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C)
     ```

    |參數|說明|
    |---|---|
    |N|輸出的行數|
    |M|輸出的列數，如果沒有就默認爲 N|
    |k|對角線的下標，默認爲0：表示的是主對角線，負數表示的是低對角，正數表示的是高對角|
    |dtype|數據的類型|
    |order|{‘C’，‘F'}：輸出的數組的形式是按照C語言的行優先’C'，還是按照Fortran形式的列優先‘F'存儲在內存中|

     `eye()` 也是用來產生對角線元素值為1的陣列，

    與 `identity()` 不同的地方在於 `eye()` 產生的**可以不是方陣**，也可以指定對角線開始的索引。

    可以從指定的Column索引開始。
<br>
    
   - 三角矩陣：`numpy.tri()`

     `tri()` 可以用來產生對角線以下都是1的元素
<br>
     
   - 上三角矩陣 (Upper Triangular)、下三角矩陣 (Lower Triangular)：`numpy.triu()`、`numpy.tril()`

     `triu()`、`numpy.tril()` 可將對角線以上或以下的元素值設為0，也可以指定對角線起始的索引。

<br>
4. 矩陣分解 : Cholesky、QR、SVD

   NumPy 線性代數函式中提供3種矩陣分解的函式：
* Cholesky Decomposition：`numpy.linalg.cholesky()`
  - 將一個 positive-definite 的 Hermitian matrix 分解成一個下三角矩陣與其共軛轉置之乘積。<br>


* QR Factorization：`numpy.linalg.qr()`
  - 把矩陣分解成一個正交矩陣與一個上三角矩陣的積。<br>


* Singular Value Decomposition (SVD)：`numpy.linalg.svd()`
  ```python
  u, s, v = np.linalg.svd(a,full_matrices=1,compute_uv=1)
  ```
  
  |參數|說明|
  |---|---|
  |a|(M,N)矩陣|
  |full_matrices|取值是為0或者1，默認值為1，這時u的大小為(M,M)，v的大小為(N,N) 。否則u的大小為(M,K)，v的大小為(K,N) ，K=min(M,N)|
  |compute_uv|取值是為0或者1，默認值為1，表示計算u,s,v。為0的時候只計算s|

  
    u大小為(M,M)，s大小為(M,N)，v大小為(N,N)
  
    A = u * s * v

    其中s是對矩陣a的奇異值分解。 
    s除了對角元素不為0，其他元素都為0，並且對角元素從大到小排列。 
    s中有n個奇異值，一般排在後面的比較接近0，所以僅保留比較大的r個奇異值。



# 範例重點:
1. 矩陣乘積時，必須注意形狀 (shape)
2. 矩陣操作、特殊矩陣與矩陣分解在線性代數中是會時常使用到的方法


# [教學目標]

* 知道如何從 NumPy 陣列存取元素
* 了解一維與多維陣列的迴圈用法
* 初步理解陣列與其迭代物件
  - 從陣列中存取元素
  - 一維陣列的切片與索引
  - 一維陣列的的迭代
  - 多維陣列的多層迴圈
  - 攤平後再迭代多維陣列
  - np.nditer 迭代物件
  - 迭代物件的儲存方向

In [74]:
import numpy as np

## 1. 矩陣乘積

## 1.1 點積 (dot product)：`numpy.dot(a, b)`

進行點積運算須注意形狀必須注意形狀 (shape)。

若是兩個向量的點積，兩個向量的元素數目也須相同，或其中一個數目為 1 (廣播)。

若是兩個多維陣列 (矩陣) 的點積，則中間兩個大小要相同才能進行點積，例如：

$(2, 3) \cdot (3, 4) \to $ 成為 $(2, 4)$

點積的運算如下，假設 A 和 B：

$ A = 
\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{bmatrix}
$

$ B =
\begin{bmatrix}
b_{11} & b_{12} & b_{13} & b_{14}\\
b_{21} & b_{22} & b_{23} & b_{24}\\
b_{31} & b_{32} & b_{33} & b_{34}
\end{bmatrix}
$

兩個矩陣進行點積

![](dot_product.png)

In [75]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

In [76]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
np.dot(A, B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

如果形狀不符合則無法進行點積

In [79]:
np.dot(np.arange(5), np.arange(3))

ValueError: shapes (5,) and (3,) not aligned: 5 (dim 0) != 3 (dim 0)

## 1.2 內積：`numpy.inner()`

又稱純量積

一般來說內積是2個一維陣列(向量)做內積，公式如下：

$\vec a=[a_0, a_1, ..., a_{j-1}]$

$\vec b=[b_0, b_1, ..., b_{j-1}]$

$
\vec a \cdot \vec b=\sum a_0b_0+a_1b_1+...+a_{j-1}b_{j-1}
$

如果是多維陣列做乘積，那麼最後維度必須要符合，而內積結果就是其元素相乘之和。

In [ ]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(5))

In [ ]:
a

In [ ]:
b

In [ ]:
np.inner(a, b)

## 1.3 外積：`numpy.outer()`

在線性代數中外積也稱為張量積。

外積是2個一維陣列(向量)做計算，若非一維陣列的話會先進行展平(flatten)再進行外積。公式如下：

$\vec a=[a_0, a_1, ..., a_{i-1}]$

$\vec b=[b_0, b_1, ..., b_{j-1}]$

$\vec a \otimes \vec b =
\begin{bmatrix}
a_0b_0 & a_0b_1 & ... & a_0b_{j-1} \\
a_1b_0 & a_1b_1 & ... & a_1b_{j-1} \\
: & : & &: \\
: & : & &: \\
a_{i-1}b_0 & a_{i-1}b_1 & ... & a_{i-1}b_{j-1} \\
\end{bmatrix}
$

In [ ]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(6))

In [ ]:
a

In [ ]:
b

In [ ]:
np.outer(a, b)

## 1.4 矩陣乘法：`numpy.matmul()` 與 `@`

`matmul`與 `dot` 都是矩陣乘法 (Matrix Multiplication)，兩者非常類似，其相同及不同點如下：

* **如果2個都是二維陣列的話，`matmul`與 `dot` 相同。**
* 在 `matmul` 中，多維的矩陣，將前 n-2 維視為後2维的元素後，進行乘法運算。
* **`matmul` 不允許矩陣與純量相乘。**

在 Python 3.5 版本之後提供 `@` 做為矩陣相乘運算子，在多個矩陣相乘時提供更簡潔的語法。

In [ ]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

print('A',A,'\n')
print('B',B,'\n')

np.matmul(A, B)

In [ ]:
A @ B

使用 `matmul` 進行矩陣與純量相乘時會產生錯誤。

In [ ]:
np.matmul(A, 2)

In [ ]:
np.dot(A, 2)

## 2. 矩陣操作

In [ ]:
A = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
A

## 2.1 跡：`numpy.trace()`

$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
$

$
trace(A) = a_{11} + a_{22} + a_{33}
$

跡的運算可以透過 `trace()` 函式求得：

In [ ]:
np.trace(A)

## 2.2 行列式 (Determinant)：`numpy.linalg.det()`

**矩陣必為方陣 (square)**

$\vert A \vert= \begin{vmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{vmatrix}\\
= a_{11}\space a_{22}\space a_{33} + a_{12}\space a_{23}\space a_{31} + a_{13}\space a_{21}\space a_{32}
- a_{13}\space a_{22}\space a_{31} - a_{23}\space a_{32}\space a_{11} - a_{33}\space a_{12}\space a_{21}
$

圖解行列式運算 
![](https://upload.wikimedia.org/wikipedia/commons/4/4d/Determinant-columns.png)

行列式的運算可以透過 `numpy.linalg.det()` 函式求得：

In [ ]:
np.linalg.det(A)

若矩陣非方陣 (square)，則會產生錯誤

In [ ]:
np.linalg.det(np.arange(6).reshape(3,2))

## 2.3 反矩陣：`numpy.linalg.inv()`

**矩陣必為方陣 (square)**

以三階矩陣為例：

$
A = \left[\begin{array}{ccc|ccc}
a_{11} & a_{12} & a_{13} & 1 & 0 & 0\\
a_{21} & a_{22} & a_{23} & 0 & 1 & 0\\
a_{31} & a_{32} & a_{33} & 0 & 0 & 1
\end{array}\right]
$

透過高斯消去法 (Gaussian Elimination)，可以得到右邊的矩陣即為 A 的反矩陣

$
A^{-1} = \left[\begin{array}{ccc|ccc}
1 & 0 & 0 & b_{11} & b_{12} & b_{13} \\
0 & 1 & 0 & b_{21} & b_{22} & b_{23}\\
0 & 0 & 1 & b_{31} & b_{32} & b_{33}
\end{array}\right]
$

呼叫 `inv()` 函式可以得到反矩陣。

In [ ]:
np.linalg.inv(A)

若矩陣非方陣 (square)，則會產生錯誤

In [ ]:
np.linalg.inv(np.arange(6).reshape(3,2))

## 2.4 轉置 (Transpose)：`numpy.transpose()`

$
A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}
$

$
A^T = \begin{bmatrix}
a_{11} & a_{21} & a_{31} \\
a_{12} & a_{22} & a_{23} \\
a_{13} & a_{23} & a_{33}
\end{bmatrix}
$

轉置矩陣可透過呼叫 `numpy.transpose()` 函式達成。

In [ ]:
np.transpose(A)

## 2.5 `numpy.linalg.eig()`

```python
eigenvalues, eigenvectors = np.linalg.eig(x)
```

`eig()` 函式可以用來計算方陣的特徵值(eigenvalue)與特徵向量(eigenvector)。

`eig()` 回傳值有2個：eigenvalue與eigenvector。

另外 `eigvals()` 函式也可以計算特徵值。

In [80]:
B = np.array([[-2, -4, 2],[-2, 1, 2],[4, 2, 5]])
B

array([[-2, -4,  2],
       [-2,  1,  2],
       [ 4,  2,  5]])

In [81]:
w, v = np.linalg.eig(B)

In [82]:
# eigenvalues
w

array([-5.,  3.,  6.])

In [83]:
# eigenvectors
v

array([[ 0.81649658,  0.53452248,  0.05842062],
       [ 0.40824829, -0.80178373,  0.35052374],
       [-0.40824829, -0.26726124,  0.93472998]])

另外 `eigvals()` 函式也可以計算特徵值。

In [84]:
np.linalg.eigvals(B)

array([-5.,  3.,  6.])

## 2.6 秩：`numpy.linalg.matrix_rank()`



呼叫 `matrix_rank()` 回傳矩陣的秩(rank)，

NumPy是使用SVD(奇異值分解；singular value decomposition)來計算秩。

In [85]:
A = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
np.linalg.matrix_rank(A)

3

## 2.7 `numpy.linalg.solve()`

求解線性系統可以使用 `solve()` 函式。

In [86]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

## 3. 特殊矩陣

## 3.1 單位矩陣：`numpy.identity()`

單位矩陣是對角線元素值為1的方陣。

In [87]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 3.2 單位矩陣：`numpy.eye()`

```python
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C)
```

|參數|說明|
|---|---|
|N|輸出的行數|
|M|輸出的列數，如果沒有就默認爲 N|
|k|對角線的下標，默認爲0：表示的是主對角線，負數表示的是低對角，正數表示的是高對角|
|dtype|數據的類型|
|order|{‘C’，‘F'}：輸出的數組的形式是按照C語言的行優先’C'，還是按照Fortran形式的列優先‘F'存儲在內存中|

`eye()` 也是用來產生對角線元素值為1的陣列，

與 `identity()` 不同的地方在於 `eye()` 產生的**可以不是方陣**，也可以指定對角線開始的索引。

可以從指定的Column索引開始。

In [88]:
np.eye(5, 4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

可以從指定的Column索引開始。

In [89]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## 3.3 單對角陣列 (Diagonal)：`numpy.diagonal()` 與 `numpy.diag()`

`diagonal()` 與 `diag()` 語法基本上功能相同，

差別在於 `diagonal()` 可以另行指定軸做為第一個軸或第二個軸。

也可以使用 `array.diagonal()` 語法。

In [90]:
A = np.array([[3, 4, 0], [4, 4, 6], [0, 6, 5]])
A

array([[3, 4, 0],
       [4, 4, 6],
       [0, 6, 5]])

In [91]:
np.diagonal(A, offset=1)

array([4, 6])

也可以使用 `array.diagonal()` 語法。

In [92]:
A.diagonal(offset=1)

array([4, 6])

要特別留意的是在不同版本的 NumPy 單對角陣列的回傳值有所不同。

> In versions of NumPy prior to 1.7, this function always returned a new, independent array containing a copy of the values in the diagonal.

> In NumPy 1.7 and 1.8, it continues to return a copy of the diagonal, but depending on this fact is deprecated. Writing to the resulting array continues to work as it used to, but a FutureWarning is issued.

> Starting in NumPy 1.9 it returns a read-only view on the original array. Attempting to write to the resulting array will produce an error.

若要覆寫回傳的陣列，建議使用 `np.diagonal(a).copy()` 會是各版本相容性最高的語法。

## 3.4 三角矩陣：`numpy.tri()`

`tri()` 可以用來產生對角線以下都是1的元素

下面的例子是產生形狀(3,5)的陣列，從Column索引1開始的對角線以下元素值均為1。

In [93]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

## 3.5 上三角矩陣 (Upper Triangular)、下三角矩陣 (Lower Triangular)：`numpy.triu()`、`numpy.tril()`

`triu()`、`numpy.tril()` 可將對角線以上或以下的元素值設為0，也可以指定對角線起始的索引。

In [94]:
A = np.array([[3, 4, 0], [4, 4, 6], [0, 6, 5]])
A

array([[3, 4, 0],
       [4, 4, 6],
       [0, 6, 5]])

In [95]:
np.triu(A)

array([[3, 4, 0],
       [0, 4, 6],
       [0, 0, 5]])

In [96]:
np.tril(A, 1)

array([[3, 4, 0],
       [4, 4, 6],
       [0, 6, 5]])

## 4. 矩陣分解 (Matrix Decomposition)

NumPy 線性代數函式中提供3種矩陣分解的函式：
* Cholesky Decomposition：`numpy.linalg.cholesky()`
  - 將一個 positive-definite 的 Hermitian matrix 分解成一個下三角矩陣與其共軛轉置之乘積。<br>


* QR Factorization：`numpy.linalg.qr()`
  - 把矩陣分解成一個正交矩陣與一個上三角矩陣的積。<br>


* Singular Value Decomposition (SVD)：`numpy.linalg.svd()`
  ```python
  u, s, v = np.linalg.svd(a,full_matrices=1,compute_uv=1)
  ```
  
  |參數|說明|
  |---|---|
  |a|(M,N)矩陣|
  |full_matrices|取值是為0或者1，默認值為1，這時u的大小為(M,M)，v的大小為(N,N) 。否則u的大小為(M,K)，v的大小為(K,N) ，K=min(M,N)|
  |compute_uv|取值是為0或者1，默認值為1，表示計算u,s,v。為0的時候只計算s|

  
    u大小為(M,M)，s大小為(M,N)，v大小為(N,N)
  
    A = u * s * v

    其中s是對矩陣a的奇異值分解。 
    s除了對角元素不為0，其他元素都為0，並且對角元素從大到小排列。 
    s中有n個奇異值，一般排在後面的比較接近0，所以僅保留比較大的r個奇異值。

In [97]:
B = np.array([[1, 2],[2, 50]])
B

array([[ 1,  2],
       [ 2, 50]])

## 4.1 `numpy.linalg.cholesky()`

In [98]:
np.linalg.cholesky(B)

array([[1.        , 0.        ],
       [2.        , 6.78232998]])

## 4.2 `numpy.linalg.qr()`

In [99]:
q, r = np.linalg.qr(B)

In [100]:
q

array([[-0.4472136 , -0.89442719],
       [-0.89442719,  0.4472136 ]])

In [101]:
r

array([[ -2.23606798, -45.61578674],
       [  0.        ,  20.57182539]])

## 4.3 `numpy.linalg.svd()`

In [102]:
u, s, vh = np.linalg.svd(B)

In [103]:
u

array([[ 0.04071476,  0.99917081],
       [ 0.99917081, -0.04071476]])

In [104]:
s

array([50.08149711,  0.91850289])

In [105]:
vh

array([[ 0.04071476,  0.99917081],
       [ 0.99917081, -0.04071476]])

# Numpy 運算

從陣列中存取元素

In [106]:
# 從陣列中存取元素



L = [0, 1, 8]

print(L)
print(L[-1]) # 8
print(L[0]) # 0
print(L[1:3]) # [1, 8]


[0, 1, 8]
8
0
[1, 8]


In [107]:
a = np.arange(3) ** 3

print(a)
print(a[-1]) # 8
print(a[0]) # 0
print(a[1:3]) # [1 8]

[0 1 8]
8
0
[1 8]


一維陣列的切片與索引

In [108]:
# 一維陣列的切片與索引

import numpy as np 

data = np.array([1, 2, 3])

print(data[0]) # 取出第 0 個
print(data[1]) # 取出第 1 個
print(data[0:2]) # 第 0 - 1 個
print(data[1:]) # 第 1 到最後一個
print(data[-2:]) # 倒數第二到最後一個

1
2
[1 2]
[2 3]
[2 3]


一維陣列的的迭代

In [109]:
# 一維陣列的的迭代

import numpy as np 

a = np.arange(3) ** 3

for i in a:
    print(i)
# 0
# 1 
# 8

0
1
8


多維陣列的多層迴圈

In [110]:
# 多維陣列的多層迴圈

import numpy as np 

a = np.arange(6).reshape(3, 2)

for row in a:
    print(row)
# [0 1]
# [2 3]
# [4 5]

[0 1]
[2 3]
[4 5]


In [111]:
for row in a:
    for d in row:
        print(d)
# 0
# 1
# 2
# 3
# 4
# 5

0
1
2
3
4
5


攤平後再迭代多維陣列

In [112]:
# 攤平後再迭代多維陣列

import numpy as np 

a = np.arange(6).reshape(3, 2)

for d in a.flat:
    print(d)

0
1
2
3
4
5


np.nditer 迭代物件

In [113]:
# np.nditer 迭代物件

import numpy as np 

a = np.arange(6).reshape(3, 2)

for d in np.nditer(a):
    print(d)

0
1
2
3
4
5


迭代物件的儲存方向

In [114]:
# 迭代物件的儲存方向

a = np.arange(6).reshape(3, 2)

for d in np.nditer(a, order='C'):
    print(d)


0
1
2
3
4
5


In [115]:
a = np.arange(6).reshape(3, 2)

for d in np.nditer(a, order='F'):
    print(d)


0
2
4
1
3
5
