# 範例目標:

1. 陣列內容 (Array contents)<br>
   - nan判斷：`isnan()`
   - 有限數 (finite number)判斷：`isfinite()`
   - 無限數判斷：`isinf()`、`isposinf()`、`isneginf()`
   - 時間(nat(NaT) = not a time)判斷：`isnat()`<br>
   

2. 陣列型別偵測 (Array type testing)<br>
   - `isscalar()` (傳入值須為**元素**)<br>
   - 實數複數判斷：`isreal()`、`iscomplex()`、`isrealobj()`、`iscomplexobj（）`<br>
     - 判斷整個**陣列物件**是否為實數或是複數物件
   
   
   
3. 比較 (Comparison)<br>
   - 2 個陣列是否相同：`np.array_equal()`、`np.array_equiv()`<br>
   - 等於/不等於、大於/大於或等於、小於/小於或等於

|函式|說明|
|---|---|
|np.equal()|等於|
|np.not_equal()|不等於|
|np.greater()|大於|
|np.greater_equal()|大於或等於|
|np.less()|小於|
|np.less_equal()|小於或等於|

4. 邏輯操作 (Logical operations)

   邏輯比較函式都是 element-wise，比較 2 個陣列元素。如果 2 個陣列的形狀不同的話，必須符合廣播 (broadcasting) 規則。

|Logical operation|函式|
|---|---|
|AND|np.logical_and()|
|OR|np.logical_or()|
|NOT|np.logical_not()|
|XOR|np.logical_xor()|

5. Truth 值測試 (Truth value testing)
   - `np.all()` 是 AND 邏輯的比較<br>
   - `np.any()` 是 OR 邏輯的比較

# 範例重點:
1. 在此介紹的函數應注意是否為 element-wise 的比較邏輯，因不同邏輯產生的輸出會不相同<br>


2. np.inf 表示**無限數**，np.nan表示 **Not a Number**<br>


3. 廣播 (broadcasting) 規則:<br>

   對兩個數組，分別比較他們的每一個維度（若其中一個數組沒有當前維度則忽略），滿足：

   - 數組擁有相同形狀。
   - 當前維度的值相等。
   - **當前維度的值有一個是 1。**
   
   
# [教學目標]

* 正確的使用 NumPy 中的算術運算
* 了解 NumPy 陣列與數學矩陣的關係
* 知道 NumPy 與 SciPy 差異為何<br>
 - 相同大小的陣列運算
 - 常數與陣列運算
 - 不同大小的陣列運算
 - 陣列運算與容器運算的差異
 - 用於陣列的矩陣運算
 - 轉置矩陣
 - 逆矩陣
 - 矩陣對角線和
 - 解線性矩陣方程式
 - 內積

In [1]:
import numpy as np

## 1. 陣列內容

## 1.1 `isnan()`

呼叫 `isnan()` 函式判斷陣列元素是否為 nan，如果是的話回傳 True，否則回傳 False。

`numpy.nan` 與 `numpy.NAN` 都是 NumPy 常數，代表 Not a Number (在官方文件中建議統一使用小寫的 `nan`)。

In [2]:
np.isnan(np.array([1.0, np.nan, 3.0]))

array([False,  True, False])

### 1.2 `isfinite()`

判斷陣列元素是否為有限數 (finite number)，如果是的話回傳 True，如果元素值為正無限數、負無限數、或是 nan 則回傳 False。

In [3]:
np.isfinite(1.0)

True

In [4]:
np.isfinite(np.nan)

False

## 1.3 `isinf()`、`isposinf()`、`isneginf()`

判別元素是否為無限數。

|函式|說明|
|---|---|
|isinf()|判斷陣列元素是否為正無限數或負無限數|
|isposinf()|判斷陣列元素是否為正無限數|
|isneginf()|判斷陣列元素是否為負無限數|
<br>

在下列範例中我們會用到 NumPy 內建常數 (Constants) 來示範，無限數相關的常數如下表：

|常數|說明|別名|
|---|---|---|
|np.inf|正無限數| np.Inf, np.Infinity, np.PINF, np.infty|
|np.Inf|正無限數||
|np.Infinity|正無限數||
|np.PINF|正無限數||
|np.infty|正無限數||
|np.NINF|負無限數||


NumPy 文件建議正無限數使用 `np.inf` (小寫)。

In [5]:
np.isinf([np.inf, -np.inf, 1.0, np.nan, np.PINF])

array([ True,  True, False, False,  True])

In [6]:
np.isposinf(np.PINF)

True

In [7]:
np.isneginf(np.NINF), np.isneginf(np.nan)

(True, False)

## 1.4 `isnat()`

`isnat()` 的 nat (NaT) 是 **not a time** 的意思，用來判別陣列元素是否為日期時間。若非日期時間 (包括 datetime 或 timedelta) 的話回傳 True，若是的話則回傳 False。

In [8]:
np.isnat(np.array(["NaT", "2020-06-26"], dtype="datetime64[ns]"))

array([ True, False])

## 2. 陣列型別偵測

## 2.1 `isscalar()`

如果陣列元素為純量或是數字物件 (例如實數、複數、有理數) 、內建常數、字串的話，`isscalar()` 回傳 True 。<br>

需要留意的是 `isscalar()` 不是 element - wise 的，所以傳入值須為**元素**。

數字物件的詳細說明，參照 [PEP 3141](https://www.python.org/dev/peps/pep-3141/)。

如果傳傳整個陣列的話，會回傳 False。

傳入 0 維陣列的話，仍然會回傳 False。

In [9]:
a = np.array([1, 2, 3])

In [10]:
np.isscalar(a)

False

In [11]:
np.isscalar(np.array(3.0))

False

傳入內建常數 `np.pi`，回傳 True。

In [12]:
np.isscalar(np.pi)

True

## 2.2 `isreal()`、`iscomplex()`、`isrealobj()`、`iscomplexobj（）`

判斷輸入的陣列元素為實數 (`isreal()`) 或是複數 (`iscomplex()`)。

與上面 2 個函式類似的 `isrealobj()`、`iscomplexobj（）`，不同之處在於是判斷整個**陣列物件**是否為實數或是複數物件。

In [13]:
# 包含實數與複數的陣列
b = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

In [14]:
np.isreal(b)

array([False,  True,  True,  True,  True, False])

In [15]:
np.iscomplex(b)

array([ True, False, False, False, False,  True])

In [16]:
# 陣列中有複數，所以回傳 False
np.isrealobj(b)

False

In [17]:
np.iscomplexobj(b)

True

In [18]:
# 陣列中全部是實數
np.isrealobj(np.array([1, 2.0, 3.1]))

True

## 3. 比較

## 3.1 比較 2 個陣列是否相同：`np.array_equal()`、`np.array_equiv()`

|函式|說明|
|---|---|
|np.array_equal()|若兩個陣列形狀與元素值均相同，回傳 True|
|np.array_equiv()|兩個陣列形狀元素值均相同，回傳 True；<br />如果兩個陣列維度不同的話，須符合廣播規則，且元素值均相同，則回傳 True|

兩個函式不同之處在於 `array_equal()` 需要**形狀完全一樣且元素值皆相同才為 True**。

In [19]:
#array_equal()形狀完全一樣且元素值皆相同
np.array_equal(np.array([1, 2, 3]), np.array([1, 2, 3]))

True

In [20]:
np.array_equiv(np.array([1, 2, 3]), np.array([[1, 2, 3], [1, 2, 3]]))

True

In [21]:
np.array_equiv(np.array([1, 1, 1]), np.array([1]))

True

## 3.2 比較：等於/不等於、大於/大於或等於、小於/小於或等於

|函式|說明|
|---|---|
|np.equal()|等於|
|np.not_equal()|不等於|
|np.greater()|大於|
|np.greater_equal()|大於或等於|
|np.less()|小於|
|np.less_equal()|小於或等於|

上列的函式均可以比較兩個形狀相同的陣列，或是比較符合廣播規則的兩個陣列，若元素值相同的話就回傳 True。

比較時均是 element-wise 的比較。

In [22]:
# 形狀與元素值均相同
np.equal(np.array([1, 2, 3]), np.array([1, 2, 3]))

array([ True,  True,  True])

In [23]:
# 符合廣播規則的相等
np.equal(np.array([1, 1, 1]), np.ones(1))

array([ True,  True,  True])

In [24]:
# 不等於的比較，符合廣播規則
np.not_equal([1, 2], [[1, 3],[1, 4]])

array([[False,  True],
       [False,  True]])

## 4. 邏輯操作

邏輯比較函式都是 element-wise，比較 2 個陣列元素。如果 2 個陣列的形狀不同的話，必須符合廣播 (broadcasting) 規則。

|Logical operation|函式|
|---|---|
|AND|np.logical_and()|
|OR|np.logical_or()|
|NOT|np.logical_not()|
|XOR|np.logical_xor()|

In [25]:
x = np.array([True, True, False, False])
y = np.array([True, False, True, False])

In [26]:
np.logical_and(x, y)

array([ True, False, False, False])

In [27]:
np.logical_or(x, y)

array([ True,  True,  True, False])

In [28]:
np.logical_not(x)

array([False, False,  True,  True])

In [29]:
np.logical_xor(x, y)

array([False,  True,  True, False])

## 5. `np.all()`、`np.any()`

針對軸 (axis) 進行比較，兩個函式不同的地方在於:

`np.all()` 是 AND 邏輯的比較，<br>
`np.any()` 是 OR 邏輯的比較。

以下的值均認定為非 0，也就是屬於 True：True、NaN、正無限值、負無限值

In [30]:
np.all([-1, np.nan, 5])

True

In [31]:
np.all([-1, 4, 0])

False

In [32]:
np.any([[True, False], [True, True]])

True

In [33]:
np.any([[True, False], [False, False]], axis=0)

array([ True, False])

# NumPy 運算

**相同大小的陣列運算**

In [34]:
# 相同大小的陣列運算

import numpy as np

a = np.array( [20,30,40,50] )
b = np.arange( 4 )

print(a + b)
print(a * b)

[20 31 42 53]
[  0  30  80 150]


**常數與陣列運算**

In [35]:
# 常數與陣列運算

import numpy as np

a = np.array( [20,30,40,50] )

print(a - 2)
print(a / 10)

[18 28 38 48]
[2. 3. 4. 5.]


**不同大小的陣列運算**

In [36]:
# 不同大小的陣列運算

import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

print(data + ones_row)

[[2 3]
 [4 5]
 [6 7]]


**陣列運算與容器運算的差異**

In [37]:
# 陣列運算與容器運算的差異

a = np.array( [20,30,40,50] )
print(a + 1)

a = [20, 30, 40, 50]
b = []
for i in a:
    b.append(i+1)
print(b)

[21 31 41 51]
[21, 31, 41, 51]


**用於陣列的矩陣運算**

In [38]:
# 用於陣列的矩陣運算

a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
y = np.array([[5.], [7.]])
print(y)

[[1. 2.]
 [3. 4.]]
[[5.]
 [7.]]


In [39]:
#轉置矩陣
print(a.transpose())

#逆矩陣
print(np.linalg.inv(a))

#矩陣對角線和
print(np.trace(a))

#解線性矩陣方程式
print(np.linalg.solve(a, y))

[[1. 3.]
 [2. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
5.0
[[-3.]
 [ 4.]]


**內積:**

矩陣元素相乘（element - wise）只有numpy.multiply() 及 *。

`np.multiply(A, B)` == `A * B`

其他np.dot()，np.matmul()均是矩陣乘法。